// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ46VnX1lBdsVM_72NrHSJVYZVQ28vndg',
    appId: '1:522907829647:web:0d1d605ef665ee2fc2f7fa',
    messagingSenderId: '522907829647',
    projectId: 'movie-scout-a6608',
    authDomain: 'movie-scout-a6608.firebaseapp.com',
    storageBucket: 'movie-scout-a6608.firebasestorage.app',
    measurementId: 'G-ZH9V9H36NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrt2RdPnAGkFbrmDW2-mn5wnkeCTFJY04',
    appId: '1:522907829647:android:ad24946d8fa25054c2f7fa',
    messagingSenderId: '522907829647',
    projectId: 'movie-scout-a6608',
    storageBucket: 'movie-scout-a6608.firebasestorage.app',
  );
}
