name: Flutter Tests & Codacy Coverage

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'any'
          fetch-depth: 0

      - name: Install dependencies
        run: flutter pub get

      - name: Install Realm binaries
        run: dart run realm install

      - name: Create dummy .env file
        run: touch .env

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
